Still some errors, but partclone is started

diff --git a/patch/etc/init.d/S99custom b/patch/etc/init.d/S99custom
--- a/patch/etc/init.d/S99custom
+++ b/patch/etc/init.d/S99custom
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 mkdir /images
-mount /dev/disk/by-label/IMAGES /images -o ro -t ext2
+mount /dev/disk/by-label/IMAGES /images -o ro -t ntfs
 
 
 if [[ ! -z $isdebug ]]; then
@@ -13,8 +13,20 @@ fi
 
 cd /images
 echo "Select image to restore:"
-select d in $(ls | grep -v lost+found); do test -n "$d" && break; echo ">>> Invalid Selection"; done
+select d in $(ls -1dN -- */); do test -n "$d" && break; echo ">>> Invalid Selection"; done
+
+if [[ -z $d ]]; then
+    echo "No image found. Cannot continue..."
+    exit 1
+fi
+
 export img=$(basename $d)
+
+export type=down
+export imgType=n
+export osid=9  # Windows 10, check /usr/share/fog/lib/funcs.sh for values
+export imgFormat=0
+export imgPartitionType=all
 
 echo "" > /bin/fog.checkin
 echo "" > /bin/fog.mount
@@ -33,5 +45,9 @@ if [[ -z $isdebug ]]; then
     echo "##############################################################################"
     usleep 60000000
     reboot
+    exit 0
 fi
 
+echo "fog.download finished! (Exit bash to reboot)"
+bash
+reboot
